import 'package:cloud_firestore/cloud_firestore.dart';

/// Represents a match document stored at `matches/{matchId}` in Firestore.
///
/// The [matchId] is deterministically generated by sorting both user UIDs
/// alphabetically and joining them with an underscore.
class MatchDocument {
  final String matchId;
  final List<String> users;
  final DateTime createdAt;
  final String? lastMessage;
  final DateTime? lastMessageAt;
  final Map<String, int> unreadCount;

  const MatchDocument({
    required this.matchId,
    required this.users,
    required this.createdAt,
    this.lastMessage,
    this.lastMessageAt,
    required this.unreadCount,
  });

  /// Generates a deterministic match ID from two user UIDs.
  ///
  /// Sorts the UIDs alphabetically and joins them with an underscore.
  static String generateMatchId(String uid1, String uid2) {
    final sorted = [uid1, uid2]..sort();
    return sorted.join('_');
  }

  /// Converts this [MatchDocument] to a Firestore-compatible map.
  Map<String, dynamic> toFirestore() {
    return {
      'matchId': matchId,
      'users': users,
      'createdAt': Timestamp.fromDate(createdAt),
      if (lastMessage != null) 'lastMessage': lastMessage,
      if (lastMessageAt != null)
        'lastMessageAt': Timestamp.fromDate(lastMessageAt!),
      'unreadCount': unreadCount,
    };
  }

  /// Creates a [MatchDocument] from a Firestore document snapshot.
  factory MatchDocument.fromFirestore(
      DocumentSnapshot<Map<String, dynamic>> doc) {
    final data = doc.data()!;
    return MatchDocument(
      matchId: data['matchId'] as String,
      users: List<String>.from(data['users'] as List),
      createdAt: (data['createdAt'] as Timestamp).toDate(),
      lastMessage: data['lastMessage'] as String?,
      lastMessageAt: data['lastMessageAt'] != null
          ? (data['lastMessageAt'] as Timestamp).toDate()
          : null,
      unreadCount: Map<String, int>.from(data['unreadCount'] as Map),
    );
  }

  /// Creates a [MatchDocument] from a raw map.
  factory MatchDocument.fromMap(Map<String, dynamic> data) {
    return MatchDocument(
      matchId: data['matchId'] as String,
      users: List<String>.from(data['users'] as List),
      createdAt: data['createdAt'] is Timestamp
          ? (data['createdAt'] as Timestamp).toDate()
          : data['createdAt'] as DateTime,
      lastMessage: data['lastMessage'] as String?,
      lastMessageAt: data['lastMessageAt'] != null
          ? (data['lastMessageAt'] is Timestamp
              ? (data['lastMessageAt'] as Timestamp).toDate()
              : data['lastMessageAt'] as DateTime)
          : null,
      unreadCount: Map<String, int>.from(data['unreadCount'] as Map),
    );
  }

  MatchDocument copyWith({
    String? matchId,
    List<String>? users,
    DateTime? createdAt,
    String? lastMessage,
    DateTime? lastMessageAt,
    Map<String, int>? unreadCount,
  }) {
    return MatchDocument(
      matchId: matchId ?? this.matchId,
      users: users ?? this.users,
      createdAt: createdAt ?? this.createdAt,
      lastMessage: lastMessage ?? this.lastMessage,
      lastMessageAt: lastMessageAt ?? this.lastMessageAt,
      unreadCount: unreadCount ?? this.unreadCount,
    );
  }
}
